# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: mcsheehan/android-ci-image
      
    working_directory: ~/repo

    dependencies:
      pre:
        - chmod +x gradlew
        - ANDROID_HOME=/usr/local/android-sdk-linux

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      # Download and cache dependencies
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
#          - v1-dependencies-

      - run: ./gradlew assembleDebug

#      - save_cache:
#          paths:
#            - ~/.gradle
#          key: v1-dependencies-{{ checksum "build.gradle" }}
        
      # run tests!
#      - run: gradle test
